### ISSUE TITLE
Python 3.6.x (IxNetwork8.50EA self installed) can't run samples

### ISSUE THREAD

**Issue by kkingkill** [ixiacom/ixnetwork-api-py#2]
LAB1: IxNetwork can't  run samples by using Python 3.6.x.  it will throw "ImportError: cannot import name 'IxNet'".
LAB2: And I only changed  the interpreter to Python 2.7.6,  samples can run.   
**note:**  I use PyCharm and git clone ixnetwork-api-py
              Do you test samples in Python 3.6.x?   According to notes, it should support Python 3.6.

**Comment by dgalan-xxia** [comment]
This was fixed in commit 581143542e37a1aba446ecd9f497b94e8ef1ce3a
